# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoid',
            field=models.CharField(default=0, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
