# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190316_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionofinterest',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
