# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 14:31
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190316_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='video',
            name='videoid',
            field=models.CharField(default=app.models.unique_order_id_generator, max_length=16, primary_key=True, serialize=False),
        ),
    ]
